### ISSUE TITLE
2주차 발표 계획

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#1]
2주차 발표는 영상으로 찍어서 자료실에 올릴 예정입니다.
이번 영상의 주제는 사용하는 라이브러리와 api에 대하여 설명할 것입니다.
어떤 것이 있을까요?

**Comment by hanzel777** [comment]
프레젠테이션 전체를 찍어야 하는 것이 아닌가요?

**Comment by hanzel777** [comment]
우리 1주차 때 만든거에서 2주차 강의자료에 영상을 시청하고 만든거기 때문에 이번주에는 더 바꿔야할 것이 없을 것 같습니다.

**Comment by bong5472** [comment]
이전 발표에서 받은 질문들의 피드백을 반영하면 좋겠습니다.

**Comment by bytecell** [comment]
Prof: 논의해가면서, 이슈 assign 을 하도록 하세요~
