### ISSUE TITLE
추천 페이지 이름 넘어감

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#100]
카페 이름이 너무 긴 경우 추천 블록에서 카페 이름이 넘어가는 버그가 있습니다

**Comment by tjddnr5932** [comment]
style="overflow:hidden;white-space:nowrap;text-overflow:ellipsis"을 하여 이름이 넘어가면 ...으로 숨겼습니다.

**Comment by hanzel777** [comment]
카페 이름에 ...이 되면 사용자가 전부를 볼 수 없기때문에 마우스를 대면 전체 이름을 볼 수 있으면 좋을 것 같습니다.
