### ISSUE TITLE
추천 페이지 이름을 넘어갈 때 블록이 전부 내려가는 오류

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#101]
추천 페이지에 카페 이름이 넘어 갈때 블록 전체가 내려가는 오류가 있었습니다. 그리하여 카페 이름 다음에 br로 띄어쓰기를 하였더니 오류가 사라졌습니다.

**Comment by hanzel777** [comment]
확인했습니다.
