### ISSUE TITLE
페이지 헤더 부분 height 조정

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#102]
페이지 헤더 부분을 기본적으로 100px로 지정해놨습니다. 헤더 부분의 높이가 일정해야 미관적으로 아릅답다 생각해서 고정해놓았으나, 헤더 아래 메인 파트에서 종종 마진값으로 인해 헤더 부분의 height가 늘어나 보이는 페이지가 있습니다. 혹시 발견되면 메인페이지의 제일 첫번째 컨텐츠를 style="margin-top:0px" 로 지정해주세요

**Comment by hanzel777** [comment]
네 알겠습니다.
