### ISSUE TITLE
마커 이미지 제작

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#106]
마커 이미지를 제작했습니다. 1순위는 빨강, 2순위는 노랑, 3순위는 파랑으로 제작해 차이를 보이게 했습니다.

**Comment by tjddnr5932** [comment]
제작한 마커를 이용하여 구현하였습니다! 확인바랍니다!

**Comment by hanzel777** [comment]
네 확인했습니다.
