### ISSUE TITLE
manual 페이지 슬라이드 부분 체크

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#112]
현재 manual 페이지를 슬라이드로 제작해 놨습니다. 한쪽은 이미지, 다른 쪽은 텍스트를 넣는 것을 생각해 슬라이드 화면을 분할해 놨습니다. 슬라이드의 내용이 채워지게 되면 꼭 css에서 border부분을 삭제해 주세요.

**Comment by tjddnr5932** [comment]
네! 삭제하였습니다!
