### ISSUE TITLE
manual 페이지로 가기 위한 버튼 추가 요청

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#114]
manual 페이지의 구성을 제작 완료했습니다. 구성은 완료 되었지만 내부의 내용들을 채워 주셔야 합니다.

그리고 메인 페이지에서 manual 페이지로 가기 위한 링크가 필요합니다. 지금 제작된 메인페이지에는 추가적으로 들어가기엔 무리가 있다고 느껴서 페이지 가운데 Make a Coffing 옆에 이미지로 How to Use? 이미지를 추가해 연결하면 좋을 것 같습니다.

흰색 글씨에 투명 배경을 사용해 이미지를 추가했습니다. 기존의 페이지 내용들의 위치를 바꾸지 않기 위해 이미지의 css에서 position : absolute 또는 fixed를 사용하는 것을 추천합니다.

**Comment by tjddnr5932** [comment]
how to use 버튼은 로그인 버튼 밑에 만들었습니다! 확인바랍니다.

**Comment by bong5472** [comment]
최종 결과물 확인 했습니다.
