### ISSUE TITLE
전체 웹 구현 및 오류 수정 완료

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#116]
전체 웹 구현 및 오류 수정이 완료되었습니다. 이제 readme를 제대로 작성하여야 할 것 같습니다.
readme에 저희 웹의 소개를 넣으면 좋을 것 같습니다.

**Comment by bong5472** [comment]
확인했습니다.

**Comment by tjddnr5932** [comment]
readme의 내용

1. 설치방법
2. 의존성
3. 실행 방법
4. 연락처

4가지를 작성하겠습니다.

**Comment by tjddnr5932** [comment]
readme의 내용에 라이선스도 추가하였습니다.
