### ISSUE TITLE
리뷰 쓰기 및 리뷰하기 기능

### ISSUE THREAD

**Issue by hanzel777** [tjddnr5932/Kim2Han_coffing#14]
마이페이지에서 사용자가 최근 방문한 카페보기 기능을 누르면 자신이 카페 추천시 방문 기록 남기기를 한 카페를 볼 수 있고 아직 리뷰를 남기지 않은 카페의 리뷰를 남길 수 있으며 리뷰를 남긴카페는 다시 자신의 리뷰를 볼 수 있도록 하는 기능을 구현하려고 합니다. 여기서 의견있으시면 부탁드립니다. 11/12 22:00쯤까지 부탁드립니다.

**Comment by tjddnr5932** [comment]
한 곳에서 자신이 방문한 카페를 볼 수 있는 것은 좋은 것 같습니다. 
제가 생각했을 때 최근 방문한 카페보기에서 카페를 누르면 다른 사람들이 작성한 리뷰를 볼수있는 기능도 만들면 좋을 거 같습니다.

**Comment by bong5472** [comment]
추천 과정에서 리뷰를 작성한 카페는 다른 마커를 사용하는 방법도 좋을것 같습니다.

**Comment by hanzel777** [comment]
추천 과정에서 리뷰를 작성한 카페 다른 마커를 사용하는 것은 수용해보겠습니다.
