### ISSUE TITLE
전문가 섭외 이슈

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#15]
리뷰 데이터를 전문가와 일반 사용자로 나눠서 데이터베이스에 저장하려고 합니다.
전문가를 섭외하는 것은 비용이나 시간이 많이 발생할 것으로 예상됩니다.
이것에 대하여 논의를 하였으면 좋겠습니다.

**Comment by hanzel777** [comment]
전문가보다 주관성이 떨어질 수 있지만 현실적 비용 측면에서 커피관련 자격증(대표적으로 바리스타 등)과 같은 인증을 통해 사용자를 나누어 리뷰 데이터를 쌓는 것도 좋을 것 같습니다.

**Comment by tjddnr5932** [comment]
네! 좋은 것 같습니다.
그러면 자격증 사진을 업로드 하여 전문가를 인증하는 방법으로 하겠습니다.
