### ISSUE TITLE
리뷰 페이지 양식

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#18]
리뷰 페이지에 들어갈 내용들에 대한 정리가 필요합니다. 현재 구상중인 내용은 카페 이름, 주소, 사진, 별점, 맛 평가도, 리뷰 정도이고 추가 시켜야 할 내용이 있는지,  또는 빠져야 할 내용이 있는지 양식에 대한 제안을 해주세요

**Comment by tjddnr5932** [comment]
자신의 위치와 얼마나 떨어져 있는지 대략적인 거리도 표시해 주면 좋을 것 같습니다.

**Comment by hanzel777** [comment]
현재 서버에서 /mypage에서 방문한 카페를 누르면 /mypage/visitedList 로 이동해서 카페의 이름과 리뷰를 남긴 카페는 전체 리뷰보기만 리뷰를 남기지 않은 카페는 리뷰쓰기와 전체 리뷰 보기를  form두개를 이용해 구현 중인데 그러면 여기서  전체 리뷰 보기가 아니라 카페 이름, 주소, 사진, 별점, 맛 평가도 text리뷰하고 자신이 설정한 위치와 얼마나 먼지에 대한 거리 표시 구현하겠습니다.

**Comment by hanzel777** [comment]
mysql에 카페 테이블도 수정할테니 필요하신분은 알려주세요

**Comment by hanzel777** [comment]
리뷰 테이블에 commet는 꼭 필요하지 않은 값으로 해두겠습니다.
