### ISSUE TITLE
추천 기능 구현

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#19]
커피 추천 기능을 구현하려고 합니다. 메인 페이지에 커핑을 누르면 추천페이지로 이동하게 되고 원두추천, 평가추천으로 나눠서 추천을 하게 만들 생각입니다. 추천 시 거리는 대략 2km로 생각중 입니다.

**Comment by hanzel777** [comment]
평가 추천시에 3/3/3/3/3을 선택한 사람이 추천을 받는다면 2/3/3/3/3 정도의 오차는 2순위로 추천해주면 좋을 것 같습니다. 또한 추천을 받은 후 카페 방문하기 기능을 추가해 방문 카페 리스트에 추가할 수 있게 하면 좋을 것 같습니다.

**Comment by tjddnr5932** [comment]
추가로 3순위를 만들어 1순위와 2순위 카페가 없으면 추천 거리 안의 모든 카페를 보여줄 것입니다.
