### ISSUE TITLE
카페 정보 보기에서 사진을 서버에서 올려야 하는데 이미지가 깨지며 찾지못합니다.

### ISSUE THREAD

**Issue by hanzel777** [tjddnr5932/Kim2Han_coffing#20]
routes에 mypage에서 <img sre="../image">에 문제가 있습니다. static이나 여러가지 방법 등 시도해보았지만 아직 방법을 찾지못해서 혹시 아시는분 있으시면 해답 부탁드립니다.

**Comment by tjddnr5932** [comment]
데이터베이스에서 서버로 사진이 안보내지는 건가요? 아니면 서버에는 올려지는데 이미지가 깨지는 건가요?

**Comment by hanzel777** [comment]
데이터베이스에 JSON배열형태로 경로를 넣어 놓으면 해당 카페의 정보를 볼 때, 경로안에 있는 JSON배열을 가져와 사진을 클라이언트에게 보내려고 했습니다.

**Comment by hanzel777** [comment]
해당 문제는 Express의 기본 제공 미들웨어 함수인 express.static에 대한 이해도 부족으로 일어 났고 어느정도 이해해서 방금 해결 되었습니다. app.use(express.static('폴더이름')); 으로 정적 으로 처리하여 폴더 내의 이미지 경로를 가져오는데 성공했습니다.

**Comment by hanzel777** [comment]
이슈 해결 되었으니 닫겠습니다.
