### ISSUE TITLE
마이페이지 v1.0 구현

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#21]
기본적으로 페이지를 3분할 후 개인정보, 개인 맛 평가도에 대한 변수를 선언해 놨습니다. 코드 마지막 script 부분에 변수로 선언 해놔서 DB에서 값을 쉽게 받게끔 시도해봤습니다. 아직 주소 부분과 리뷰 부분은 구현하지 못했습니다. 확인 후 comment 바랍니다.

**Comment by hanzel777** [comment]
확인했습니다. 서버에서 db값을 받아와서 module에 변수를 직접사용하여 값을 넣었습니다.
