### ISSUE TITLE
프론트앤드와 백앤드 결합

### ISSUE THREAD

**Issue by hanzel777** [tjddnr5932/Kim2Han_coffing#23]
오늘 되신만큼 main클론 하시거나 pull해서 html 폴더 같은 곳에 정리해서 올려주시면 내일 바로 백앤드 프론트앤드 결합하겠습니다. 한 폴더에 정리해 주시면 좋을 것 같습니다.

**Comment by hanzel777** [comment]
현재 로그인 페이지에서 회원가입 버튼이 login버튼보다 더 id password쪽에 가까이 있어서 login을 회원가입 버튼보다 더 가깝게 순서를 바꾸는게 좋을 것 같은데 괜찮으십니까? @bong5472

**Comment by bong5472** [comment]
회원가입 기능보다 로그인 기능을 많이 사용할 것이라 생각해서 실제로 로그인을 진행할 때 가운데에 버튼이 있으면 클릭이 불편하지 않을까 생각하고 구성한 것이지만, 순서를 바꿔도 상관 없을꺼라 생각합니다.
