### ISSUE TITLE
remote에 올라온 branch 질문

### ISSUE THREAD

**Issue by hanzel777** [tjddnr5932/Kim2Han_coffing#27]
현재 git에 올라온 프론트 몇 %정도 진행된 거고 어떤 코드들이 올라오고 있는지 말씀해주실 수 있나요?

**Comment by hanzel777** [comment]
@bong5472 오늘 내로 답변 주시면 감사하겠습니다.

**Comment by bong5472** [comment]
올라오지 않은 코드를 포함해서 약 50%정도 진행되어 있는 상태입니다.
