### ISSUE TITLE
사용자의 위치와 카페의 거리 계산 시 문제점

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#34]
사용자와 카페 사이의 거리를 계산할 때 카페 데이터베이스에서 모든 카페의 위/경도를 다 불러와서 사용자와의 거리를 계산해야 합니다. 이렇게 되면 데이터베이스에 카페가 많아질수록 계산 시간도 기하급수적으로 늘어납니다. 이것에 대하여 토론하고 싶습니다. 

제 생각에는 카페 데이터베이스를 지역으로 묶으면 사용자가 위치한 지역의 카페만 계산하면 될 것 같습니다.  여러분의 생각이 궁금합니다. 어떻게 할까요?

**Comment by hanzel777** [comment]
카페 데이터 베이스 테이블에 시단위의 필드를 추가하여 시 단위로 db에서 가져올때 WHERE city="청주" 같은 방법일 것 같습니다. 그러면 user 테이블과 카페 테이블 두 곳에 city라는 필드를 추가하겠습니다.

**Comment by bong5472** [comment]
좋은 생각인 것 같습니다. 위도 경도는 카페를 직접 눌러 검색할 경우에만 거리를 사용하면 될것 같습니다.
