### ISSUE TITLE
user 데이터베이스의 taste열과 cafe 데이터베이스의 cafe_review 열에 대한 2가지 방법 제시

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#35]
taste와 cafe_review열을 보면 1/1/1/1/1 이런 식으로 하나로 묶여져 있습니다. 처음에는 오차를 생각하지 않고 정확히 맛이 맞는 것만 추천하려 했지만 조금의 오차를 고려하여 추천해주려고 합니다. (예:3/3/3/3/3 경우 2/3/3/3/3 도 2순위로 추천해준다.) 그런데 이런 경우 데이터베이스에서 불러올 때마다 split을 하여 구분해 줘야 하는 번거로움이 있습니다. 
데이터베이스를 변경하여 열을 나눠서 저장하는 것이 좋을까요? 아니면 데이터베이스에서 불러와서 split으로 분리하는 것이 좋을까요?

**Comment by hanzel777** [comment]
그러면 카페와 유저 테이블의 필드 taste를 각각의 요소로 나누는게 좋을 것 같습니다.

**Comment by hanzel777** [comment]
카페 테이블의 경우 public과 pro 리뷰에 따라서 맛요소가 다르기 때문에 필드를 분리시키면 혼란스러울 것 같아 나누는것보다는 split으로 사용하는것이 좋을 것 같습니다.

**Comment by tjddnr5932** [comment]
카페 테이블 경우 분리하면 열이 많아지기는 하겠네요.. 그러면 taste와 cafe_review전부 데이터베이스에서 가져와 split으로 분리하겠습니다.
