### ISSUE TITLE
설정된 맛과 평가된 맛의 오차율

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#36]
설명을 쉽게 하기 위해 예를 들어 설명하겠습니다.
설정된 맛은 3/3/3/3/3으로 가정하고  
1순위 3/3/3/3/3 인 카페
2순위 하나의 숫자 +-1 차이나는 카페 
여기까지가 계획입니다.

3순위 (두개의 숫자 +-1차이 나는 카페) or (하나의 숫자 +-2차이나는 카페)도 추가 할수 있습니다.

몇순위까지 할 것이며 만약 3순위까지 하면 3순위는 무엇을 할것인지 같이 논의하고 싶습니다.

**Comment by hanzel777** [comment]
3순위부터는 차이가 벌어지며 원하는 맛이 아니게 될 수 있기 때문에 2순위까지의 추천이 좋을 것 같습니다.

**Comment by tjddnr5932** [comment]
3순위는 1순위와 2순위 카페가 없으면 추천 거리 안의 모든 카페를 보여주는 것이 좋을 것 같습니다.
