### ISSUE TITLE
커피숍을 추천해주기 위한 기준점 논의 - 1

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#4]
커피숍을 추천해주기 위해 
1. 커피의 맛을 5가지로 나눠서 사용자가 원하는 커피 맛과 똑같은 커피숍 추천
장점 : 사용자가 원하는 커피를 보다 정확히 알 수 있다.
단점 : 자료 수집이 어렵다. 

2. 커피의 원두로 나눠서 원하는 원두를 사용하는 커피숍 추천
장점 : 자료 수집이 수월하다.
단점 : 조리법의 차이로 인한 맛의 변화

두가지 중 선택하거나 다른 좋은 아이디어가 있나요?

**Comment by bong5472** [comment]
결국 자료 수집이 진행이 되어야 서비스를 진행할 수 있기에, 조리법 차이로 인한 맛의 변화를 감수하더라도 원두로 카페를 구별하는 방법이 더 좋다고 생각합니다.

**Comment by hanzel777** [comment]
저는 1번이 커피의 정확도가 더 높을 것이라 생각하여 사용자의 만족도 측면에서 보았을 때, 결국 데이터를 모으기 쉬워 비용과 시간이 적게 든다는 이유로 2번을 선택하게 된다면 사용자의 만족도가 낮아질 수 있으며 이를 통해 어플의 평가가 낮아질 가능성이 있으므로 비용과 시간을 투자해서 더 정확한 맛을 통해 사용자의 만족도를 높이는 것이 더 좋다고 생각합니다.

**Comment by tjddnr5932** [comment]
저도 사용자들을 위해 1번 방법이 좋은 것 같지만 비용과 시간이라는 문제점 때문에 고민입니다. 하지만 2번 방법 또한 자료 수집에 있어서 큰 어려움을 겪을 것으로 예상됩니다.  두 개의 방법 모두 문제점이 명확하여 피드백을 통한 의견 조율이 필요할 것으로 보여집니다.

**Comment by hanzel777** [comment]
그러면 금요일 맨토링때 피드백을 받고 하는게 좋을 것 같습니다.

**Comment by tjddnr5932** [comment]
피드백을 통해 커피의 맛을 통해 원두를 매칭하여 커피를 추천해주는 시스템으로 가는 것이 좋을 것 같습니다.
