### ISSUE TITLE
리뷰 작성 페이지

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#41]
리뷰 작성 페이지의 경우 많은 내용이 들어갈 필요가 없다고 생각됩니다. 따라서 페이지 자체를 작게 제작해 팝업 방식으로 팝업 방식으로 제작하면 효율적이라고 생각하는데 어떤가요?

**Comment by hanzel777** [comment]
팝업창을 이용하는 것보다 현재 방식으로 현재탭에서 사용하는것이 서버와 클라이언트의 통신면에서 효율적일 것 같습니다. 클라이언트 기준에서도 그렇다할 이득이 없기 때문에 기존의 방식으로 사용하는게 좋을 것 같습니다.
- 기존의 방식
- mypage/visitedList --> mypage/write_review --> /mypage/write_process -->mypage or mypage/visitedList

- 팝업창 방식
- mypage/visitedList  --> 새창(mypage/write_review)-->mypage/write_process --> complit_page and close --> (원래창)mypage or mypage/visitedList
