### ISSUE TITLE
현재 필요한 페이지 내용

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#44]
깃허브 사용이 익숙치 않아 올라가 있는 페이지중 제대로 적용되지 않은 페이지가 몇 개 있고 올린지 아닌지 확인못한 페이지가 몇 있습니다. 확인 후 고쳐야 될 부분과 필요한 페이지의 내용을 체크해주세요

**Comment by hanzel777** [comment]
11/18에 merge된 html파일들은 아직 확인하지 못하였고 main페이지와 맛설정페이지, 리뷰쓰기페이지가 필요합니다.

**Comment by bong5472** [comment]
확인하였고 추가적으로 merge 하겠습니다.
