### ISSUE TITLE
cafeReview.html 질문

### ISSUE THREAD

**Issue by hanzel777** [tjddnr5932/Kim2Han_coffing#48]
radar chart라고 표시된 부분이 있는데 해당 부분의 의미가 무엇이진 파악하지 못했습니다. 혹시 어떤 것을 넣기 위한 것인가요?
@bong5472

**Comment by bong5472** [comment]
래이더 차트는 각형 모양의 그래프를 말합니다. 리뷰 부분에서 자신의 맛과 카페의 데이터 화된 맛을 5각형 그래프로 시각적으로 보여주면 차이를 보여주기 좋다고 생각합니다. 아직 구현중인 단계입니다.

**Comment by hanzel777** [comment]
혹시 레이더 차트 진행 다 된 cafeReview페이지가 있으면 수정본을 merge 해주실 수 있나요?

**Comment by bong5472** [comment]
레이더 차트 자체는 구성이 되었지만 html과 srcipt파일로 이루어져 페이지에 직접적으로 적용해야 할 듯 합니다. 리뷰 페이지를 빠르게 완성시킨 후 merge 하겠습니다.

**Comment by hanzel777** [comment]
알겠습니다.
