### ISSUE TITLE
메인페이지 구성

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#50]
메인페이지 우선 merge했습니다. select Flavor, select Location, Recommendation 과 login, signIn으로 구성했습니다. 확인 바랍니다

**Comment by bong5472** [comment]
앞으로 들어갈 사진들은 jpg 파일로 페이지와 이름을 맞춰놓겠습니다.

**Comment by hanzel777** [comment]
아 mypage.html에 들어갈 사진은 mypage.jpg
login.html에 들어갈 사진은 login.jpg라는 뜻이 맞으시죠?

**Comment by bong5472** [comment]
네 맞습니다.

**Comment by hanzel777** [comment]
혹시 recommende me! 이거는 혹시 추천받기 인가요?

**Comment by bong5472** [comment]
맞습니다. 메인 페이지에 추천 받기 부분을 그 위치로 생각했습니다.

**Comment by hanzel777** [comment]
그럼 원래 결정했던것 가운데 글씨와 위에 있는  recommende me! 둘다 추천 모듈에 연결하면 될까요?

**Comment by bong5472** [comment]
일단 둘 다 모듈에 연결해 두고 추후 이미지를 수정해 가운데 버튼에 추천 모듈이 있다는 것을 알려주면 좋을 것 같습니다.
