### ISSUE TITLE
추천 페이지 구성 질문

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#52]
현재 추천 페이지에는 내 위치, 설정된 맛, 지도, 추천된 카페의 리스트가 있습니다. 리스트에 버튼을 눌렀을 때 추천 카페만 자세하게 알려주는 페이지를 제작할 예정인데, 그러면 페이지 내부의 리스트에선 어떤 내용을 넣어야 될지 고민입니다. 현재 생각중인 내용으론 카페 이름, 주소, 맛 평가도, 추천 순위 입니다. 추가하거나 빠져야 될 내용이 있으면 알려주시길 바랍니다.

**Comment by hanzel777** [comment]
- 추천시 지도페이지를 기본적으로 보여줍니다.
- 지도페이지가 보기 힘든사람들을 위해 지도 우측 상단에 리스트 버튼을 통해 리스트로 보는 페이지로 이동할 수 있습니다.
- 리스트에서는 거리순, 매칭도순(1/2순위)로 볼 수 있습니다.


정리해서 내 위치는 있어도 되고 없어도 되며 지도는 불필요합니다.
추천 맵으로 돌아갈 수 있는 버튼이 있어야합니다.
리스트를 볼 때, 한눈에 보기 쉽게 꼭 필요한 정보인 상호명, 매칭도, 유저와의 거리, 정확한 위치인 주소 가 꼭 필요하며 리스트가 너무 비면 다른 것들을 추가하면 될 것 같습니다.
리스트에 꼭 카페 정보 보기 버튼과 방문&종료 버튼을 추가해서 사용자 편의성을 높여주려고 합니다.

**Comment by hanzel777** [comment]
거리를 우선순위로 할지 매칭도를 우선순위로 할지 결정하는 버튼도 있으면 좋을 것 같습니다.
