### ISSUE TITLE
맛 선택 페이지 내용 추가

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#59]
맛 선택 페이지에서 쓸 내용이 필요합니다. 5가지 맛을 제가 서칭을 통해 적어 놓았지만, 정확하지 않은 표현이라고 생각합니다. 맛 설명에 있어서 기존 페이지에 있는 내용을 확인해주시고, 추가나 변경되어야 할  부분에 대해 조언해주세요.

**Comment by tjddnr5932** [comment]
기존 페이지 내용 확인하였습니다. 그렇게 하면 될 것 같습니다.
