### ISSUE TITLE
추천의 기준 변경

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#6]
피드백을 통하여 커피의 맛을 통해 카페를 추천하는 시스템에 문제가 발생하여 다른 추천 기준이 있어야 한다고 생각합니다.
어떤 추천 방법이 좋을 것 같은지 의논하여 봅시다.

**Comment by hanzel777** [comment]
카페를 추천하는 것이 아닌 커피를 추천하는데 기준을 맞춰서 데이터를 모으기가 거의 불가능할 것으로 보이므로 사용자가 원두를 선택하면 그 원두를 기준으로 맛이 비슷한 원두들을 쓰는 카페를 추천해주는 것이 좋을 것 같습니다.

**Comment by bong5472** [comment]
사용자들이 자신이 선호하는 원두를 알고 있다고 생각하기 어려우니, 원하는 커피의 맛을 설정하면 그에 맞는 원두를 추천해주면 좋을 것 같습니다.

**Comment by tjddnr5932** [comment]
커피의 맛으로 원두를 매칭하여 그 원두를 사용하여 만드는 커피가 있는 카페를 추천해주는 시스템인 것 같은데 좋은 것 같습니다.

**Comment by hanzel777** [comment]
네 동의합니다.

**Comment by tjddnr5932** [comment]
논의해본 결과 2가지 기준으로 커피를 추천해줍니다.

1. 커피의 맛은 원두에 영향을 받는다.
자신이 원하는 커피의 맛에 매칭되는 원두를 사용하는 커피 추천

2. 커피의 맛은 세부적으로 5가지로 나뉜다.
커피 리뷰를 바탕으로 커피를 전문가, 사용자 평가로 나눠 커피의 맛에 매칭되는 커피 추천
