### ISSUE TITLE
리뷰 작성 페이지 디자인 질문

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#60]
현재 제가 만든 리뷰 작성 페이지는 radio 태그를 별 모양으로 만들어 별을 클릭하면 그에 맞는 점수가 들어가도록 설정해놨습니다. 하지만 저의 환경에서 인위적으로 설정한 것이다 보니 css가 제대로 적용되는지 확인하기 어렵습니다. 다른 분들도 저와 마찬가지로 별 모양의 클릭 버튼이 생성되는지 확인 바랍니다. 제대로 적용되지 않는다면 코드를 수정해 재적용 해보거나 다른 바향으로 수정하고자 합니다.

**Comment by hanzel777** [comment]
write_review페이지의 별은 정상 작동하는 것 확인했습니다.

**Comment by bong5472** [comment]
문제 없음 확인되었습니다.
