### ISSUE TITLE
유저 테이블 city 첫 줄에 공백 제거 

### ISSUE THREAD

**Issue by hanzel777** [tjddnr5932/Kim2Han_coffing#62]
유저 테이블 필드 city에 저장되는 데이터의 앞에 " "(공백)이 있는 것을 @tjddnr5932 가 확인

- location_process와 mlocation_process에서 수정
- 변경 전
        const temp = loc.split(",");
        const tmp = temp.reverse();
        const city = tmp[3];

- 변경 후
        const temp = loc.split(",");
        const tmp = temp.reverse();
        const citytemp = tmp[3];
        const city = citytemp.replace(/ /g, '');

- replace에서 / /g를 통해 citytemp에서 모든 공백을 제거하고 city에 대입 후 city를 usertable에 업로드 하도록 변경되었습니다.

**Comment by tjddnr5932** [comment]
네! 확인했습니다!
