### ISSUE TITLE
Peer-Review를 바탕으로 향후 발전 방향

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#65]
Peer-Review를 바탕으로 생각한 향후 발전방향입니다. 

1. 현재 단계에서 자격증이 아닌 다른 전문가 인증은 어렵지만 추후에 서비스를 관련 직종에 대한 업무 경력을 인증하는 방향으로 발전
2. 리뷰 관리 AI도입
3. 사이드 메뉴 관련 추후 서비스 안정화 후 넣을 예정
4. 리뷰 데이터를 이용하여 추천해주는 서비스이기 때문에 데이터를 모으기 위해 로그인은 어쩔 수 없는 선택이지만 추후 리뷰 데이터가 많이 쌓이게 된다면 비로그인 기능 추가

**Comment by bong5472** [comment]
현재 개발 일정으로는 불가능하다고 생각됩니다. 추후 서비스 확장 방향으로 생각하겠습니다.
