### ISSUE TITLE
recommendMap.js 마커를 추가하였습니다.

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#66]
추천 시 맵에 마커가 1순위, 2순위까지 되어 있어서 3순위로 추천 거리 안의 모든 카페를 표시할 마커를 추가하였습니다.

**Comment by hanzel777** [comment]
확인했습니다. 이제 확정적으로 1/2/3 순위에 사용할 marker image를 구하면 될 것 같습니다.

**Comment by bong5472** [comment]
마커 이미지는 강조되는 색을 사용하거나(ex. 빨강, 파랑, 노랑) 같은 색의 밝기를 줄이는 방법이 좋을 것 같습니다.
