### ISSUE TITLE
radar chart 원활한 표기 안됨

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#77]
추천 페이지에서 radar chart의 내용들이 5점 만점으로 나오는 것이 아닌 각 내용 중 최대의 값으로 그려지는 걸 확인했습니다.

**Comment by hanzel777** [comment]
확인했고 이가 개발의도와 맞지 않는지는 몰랐습니다. 개발 일정에 맞춰서 수정할 수 있으면 수정해주시면 좋을 것 같으며 꼭 수정하지는 않아도 될 것 같습니다.

**Comment by bong5472** [comment]
radar chart의 javascript 부분에서 scale{ max : 5}를 추가해 해결했습니다.
