### ISSUE TITLE
manual 페이지 제작

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#78]
처음 사용하는 user들을 위해 메인 페이지에 manual 버튼을 만들어 설명을 추가해보고자 합니다. 기존 개발 일정에는 없는 부분이기에, 기존 일정이 일찍 마무리 되면 시도해보고자 합니다.

**Comment by hanzel777** [comment]
manual 버튼은 헤더에 하나 추가하여 경로만 만들면 되기때문에 다음주 평일까지만 완성된다면 목요일에 시험이라 금요일에 추가시키도록 하겠습니다.
