### ISSUE TITLE
추천 시 카페 리스트에서 raider chart가 보이지 않는 오류

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#79]
추천 시 카페 리스트에서 raider chart가 보이지 않습니다. 확인부탁드립니다.

**Comment by hanzel777** [comment]
radar chart에는 문제가 없으며 아마 mysql에 문제가 있을 것이라고 생각합니다. F12를 눌러 개발자도구에서 어떤 문제가 있는지 확인하시고 mysql에 잘못된 것이 있으면 수정해보시면 될 것 같습니다.

**Comment by tjddnr5932** [comment]
확인해 보니 데이터베이스가 잘못되어 있었습니다;; 확인 후 수정하였습니다. 감사합니다!
