### ISSUE TITLE
selectFlavor 페이지 브랜드 설명 부분 내용 확인

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#80]
selectFlavor 페이지 아래 부분에 맛 설명을 위한 브랜드 설명 부분을 만들어 둔 상태입니다. 현재 6개의 브랜드를 생각 중이고, 각 div안에 브랜드 radar chart, 브랜드 로고, 간략한 설명을 넣을 예정입니다.  브랜드의 radar chart는 고정되는 값을 활용하기 때문에 jpg 이미지로 활용하겠습니다.

**Comment by tjddnr5932** [comment]
확인하였습니다! 6개 정도면 충분할 것 같습니다.
