### ISSUE TITLE
css 파일 이름 변경

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#81]
기존의 css파일을 html 파일과 같은 이름으로 설정해 놓았으나, 수정 과정에서 파일 이름이 변경된 경우를 확인했습니다. 특정 css파일을 찾기가 어려워졌는데 특별한 이유가 있는 건가요?

**Comment by hanzel777** [comment]
원래 서버에 있던 js 파일과 이름을 맞춰서 변경된 것들이 몇개 있으며 회원가입의 경우는 signup으로 수정하여서 일부 변경이 있었습니다.

**Comment by bong5472** [comment]
이름이 바뀌면 혼란 되는 부분이 생겨서 미리 notice 하면 좋을 것 같습니다.
