### ISSUE TITLE
원두 추천 리스트에서 거리 우선 순위를 누르면 에러가 발생합니다.

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#87]
원두 추천 리스트에서 거리 우선 순위를 누르면 에러가 발생합니다. 왜 이러는지 모르겠습니다.

**Comment by hanzel777** [comment]
어떤식으로 버그가 일어나는지 개발자도구와 콜솔로그를 통해 확인해주시면 좋을 것 같습니다.
이것또한 mysql문제로 보입니다.

**Comment by tjddnr5932** [comment]
네 mysql 문제였습니다. 감사합니다!
