### ISSUE TITLE
자신의 위치를 설정할 때 맵 마커를 수정하였습니다.

### ISSUE THREAD

**Issue by tjddnr5932** [tjddnr5932/Kim2Han_coffing#92]
자신의 위치를 설정할 때 맵 마커가 현재위치만 표시 되어있습니다. 자신의 위치가 설정되어있지 않을 때 gps를 사용하여 현재위치 마커를 표시하고 자신의 위치가 설정되어 있을 때 설정된 위치 마커를 표시하게 만들었습니다.

**Comment by hanzel777** [comment]
확인했습니다.
