### ISSUE TITLE
데이터베이스 제작

### ISSUE THREAD

**Issue by bong5472** [tjddnr5932/Kim2Han_coffing#97]
현재 데이터베이스를 제작하고 있습니다. 충북대학교를 기준으로 가까운 순으로 입력하고 있습니다. 최종 목표는 300개의 카페 데이터 확보입니다.

**Comment by bong5472** [comment]
싱글 데이터는 기본값으로 0으로 두고 있고 주소와 좌표는 구글 맵의 정보를 토대로 작성하겠습니다.

**Comment by hanzel777** [comment]
네 그정도면 적당할 것 같습니다.
